name: WizardStaffs
version: '${project.version}'
main: org.randomlima.wizardstaffs.WizardStaffs
api-version: '1.20'
commands:
  wsreload:
    permission: ws.admin
    usage: /<command>
  wsgetstaff:
    permission: ws.admin
    usage: "/wsgetstaff <name> <model data>"
  wsgetrune:
    permission: ws.admin
    usage: "/wsgetrune <name> <level>"